apiVersion: v1
clusters:
- cluster:
    certificate-authority: C:\Users\samou\.minikube\ca.crt
    extensions:
    - extension:
        last-update: Thu, 23 May 2024 19:30:40 CEST
        provider: minikube.sigs.k8s.io
        version: v1.33.1
      name: cluster_info
    server: https://127.0.0.1:53593
  name: minikube
contexts:
- context:
    cluster: minikube
    extensions:
    - extension:
        last-update: Thu, 23 May 2024 19:30:40 CEST
        provider: minikube.sigs.k8s.io
        version: v1.33.1
      name: context_info
    namespace: default
    user: minikube
  name: minikube
current-context: minikube
kind: Config
preferences: {}
users:
- name: minikube
  user:
    client-certificate: C:\Users\samou\.minikube\profiles\minikube\client.crt
    client-key: C:\Users\samou\.minikube\profiles\minikube\client.key
